
# generated by stc
# date: 2012/10/30 13:42:42

package require turbine 0.0.6
namespace import turbine::*


proc swift:constants {  } {
    turbine::c::log "function:swift:constants"
    global c:i_1
    turbine::allocate c:i_1 integer
    turbine::store_integer ${c:i_1} 1
}

package require sleep1 0.0.1


proc swift:main {  } {
    turbine::c::log "enter function: main"
    set stack 0
    turbine::allocate u:bound integer
    turbine::allocate u:sleepTime float
    turbine::allocate_container t:4 integer
    # Value __ov___t0-0 with type $string was defined
    # Value __ov_bound-1 with type $int was defined
    # Value __ov___t2-2 with type $string was defined
    # Value __ov_sleepTime-3 with type $float was defined
    global c:i_1
    # Swift l.9: assigning expression to bound
    set optv:__t0-0 [ turbine::argv_get_impl "bound" ]
    set optv:bound-1 [ turbine::check_str_int ${optv:__t0-0} ]
    turbine::store_integer ${u:bound} ${optv:bound-1}
    # Swift l.10: assigning expression to sleepTime
    set optv:__t2-2 [ turbine::argv_get_impl "sleeptime" ]
    set optv:sleepTime-3 [ turbine::check_str_float ${optv:__t2-2} ]
    turbine::store_float ${u:sleepTime} ${optv:sleepTime-3}
    turbine::rangestep ${stack} [ list ${t:4} ] [ list ${c:i_1} ${u:bound} ${c:i_1} ]
    turbine::c::rule main-foreach_arr_wait0 [ list ${t:4} ] ${turbine::LOCAL} [ list main-foreach_arr_wait0 ${stack} ${u:sleepTime} ${t:4} ]
}


proc main-foreach_arr_wait0 { stack u:sleepTime t:4 } {
    set tcltmp:contents [ adlb::enumerate ${t:4} members all 0 ]
    foreach u:i ${tcltmp:contents} {
        turbine::allocate u:y float
        # Swift l.14: assigning expression to y
        sleep1::c_sleep ${stack} [ list ${u:y} ] [ list ${u:sleepTime} ]
    }
}

turbine::defaults
turbine::init $engines $servers
turbine::start swift:main swift:constants
turbine::finalize

