
CC=mpixlc

all: hellompi hellompi2


hellompi: hellompi.c
	$(CC) -O3 -o hellompi hellompi.c


hellompi2: hellompi2.c
	$(CC) -O3 -o hellompi2 hellompi.c


clean:
	/bin/rm -rf hellompi hellompi2 LOG.*



